#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "dev"  ] || [ "$branch" = "main" ] ;then
  echo "🚫 You can't commit directly to $branch branch. Please create your own branch and use Pull request instead."
  exit 127
fi

echo 'Styling, testing and building your project before committing...'

npx lint-staged
